name: Build and test UPM packages for platforms

on:
  pull_request:
    branches-ignore:    
      - 'main'
  # Ignore PRs targetting main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check Unity version requird by the package
  validate-environment:
    name: Get Unity Version from UPM package
    uses: realitycollective/reusableworkflows/.github/workflows/getunityversionfrompackage.yml@main
    with:
      build-target: windows

  # Check Unity Hub and Editor Environment
  Setup-Unity:
    name: Validate Unity Install
    needs: validate-environment
    uses: realitycollective/reusableworkflows/.github/workflows/validateunityinstall.yml@main
    with:
      build-target: windows
      unityversion: ${{ needs.validate-environment.outputs.unityversion }}

  # Run Unity unit tests defined in the package
  Run-Unit-Tests:
    name: Run Unity Unit Tests
    needs: Setup-Unity
    uses: realitycollective/reusableworkflows/.github/workflows/rununityunittests.yml@main
    with:
      build-target: windows
      unityversion: ${{ needs.Setup-Unity.outputs.unityeditorversion }}
      dependencies: '[{"development": "github.com/realitycollective/com.realitycollective.buildtools.git"},{"development": "github.com/realitycollective/com.realitytoolkit.core.git"},{"development": "github.com/realitycollective/com.realitycollective.utilities.git"},{"development": "github.com/realitycollective/com.realitytoolkit.service-framework.git"}]'
    secrets:
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_PAT: ${{ secrets.GIT_PAT }}
